version: '3'
services:
  elasticsearch:
    image: elasticsearch:7.17.15
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9300:9300"

  logstash:
    image: logstash:7.17.15
    container_name: logstash
    volumes:
      - /home/verhovensky/ELK:/usr/share/logstash/pipeline
    ports:
      - "5000:5000"
  kibana:
    image: kibana:7.17.15
    container_name: kibana
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    ports:
      - "5601:5601" 
